# Generated by Django 5.0.6 on 2024-06-25 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0002_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
