# Generated by Django 5.0.6 on 2024-06-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0008_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_account', models.CharField(max_length=20)),
                ('mobile_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
