# Generated by Django 5.0.6 on 2024-06-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0010_expert_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='decline_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
