# Generated by Django 4.2.6 on 2024-12-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0002_expert_lawyer_ohslink_content_created_at_and_more'),
        ('usalama_smart', '0014_lawyer_profile_picture_update_image_update_video_url'),
    ]

    operations = [
    ]
