# Generated by Django 4.2.6 on 2024-12-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0015_merge_20241209_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LawyerSubscription',
        ),
    ]
