# Generated by Django 4.2.6 on 2024-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usalama_smart', '0016_delete_lawyersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
